name = "colemaclean-dev-dev"
type = "webpack"
account_id = "c1f258e6a644821578a3446c7575d5a4"
workers_dev = true
route = "https://*colemaclean.dev/*"
zone_id = "566339fb99645c9cc508b55ce375a0a0"
webpack_config = "webpack.config.js"
vars = { ENVIRONMENT = "dev" }

[env.staging]
name = "colemaclean-dev-staging"
vars = { ENVIRONMENT = "staging" }
route = "https://staging.colemaclean.dev/*"

[env.production]
name = "colemaclean-dev"
vars = { ENVIRONMENT = "production" }
route = "https://*colemaclean.dev/*"

[site]
bucket = "./assets"
