name = "colemaclean"
type = "javascript"
compatibility_date = "2022-02-10"
zone_id = "566339fb99645c9cc508b55ce375a0a0"
account_id = "c1f258e6a644821578a3446c7575d5a4"
workers_dev = false

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[env.dev]
workers_dev = true

[env.staging]
route = "https://staging.colemaclean.dev/*"

[env.production]
name = "colemaclean-dev"
routes = ["https://*colemaclean.dev/*", "https://colemaclean.dev/*"]
